os: linux
dist: bionic
language: cpp

# Use Build Matrix to do lint and build seperately
env:
  jobs:
     - TASK=test CXX=g++-8
     - TASK=test CXX=g++-8 LAPSE_EXTERNAL_LDFLAGS="-DPS_BACKEND=1"
     - TASK=test CXX=g++-7
     - TASK=test CXX=g++-7 LAPSE_EXTERNAL_LDFLAGS="-DPS_BACKEND=1"
     - TASK=test CXX=g++-5

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - g++-7
      - g++-5
      - wget
      - git
      - libboost-all-dev
      - build-essential

before_install:
  - export TRAVIS=tests/travis
  - source ${TRAVIS}/travis_setup_env.sh


install:
  - pip install cpplint pylint --user `whoami`


script: ${TRAVIS}/travis_script.sh


before_cache:
  - ${TRAVIS}/travis_before_cache.sh

cache:
  directories:
    - ${HOME}/.cache/usr


notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
